vendor/github.com/joyent/triton-go/compute/errors.go, vendor/vendor.json
Errors were being fired due to Error casting in the SDK. This takes care
of those tests that were failing:
```
% make testacc TEST=./triton TESTARGS='-run=TestAccTritonFirewallRule_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./triton -v -run=TestAccTritonFirewallRule_ -timeout 120m
=== RUN   TestAccTritonFirewallRule_basic
--- PASS: TestAccTritonFirewallRule_basic (8.25s)
=== RUN   TestAccTritonFirewallRule_update
--- PASS: TestAccTritonFirewallRule_update (14.88s)
=== RUN   TestAccTritonFirewallRule_enable
--- PASS: TestAccTritonFirewallRule_enable (15.29s)
PASS
ok  	github.com/terraform-providers/terraform-provider-triton/triton	38.446s
```
=> dependecies: Bump triton-go SDK

triton/resource_machine.go
In a lot of test-cases, I received a timeout when creating an machine:
```
=== RUN   TestAccTritonMachine_basic
--- FAIL: TestAccTritonMachine_basic (653.80s)
testing.go:435: Step 0 error: Error applying: 1 error(s) occurred:
* triton_machine.test: 1 error(s) occurred:
* triton_machine.test: timeout while waiting for state to become 'running' (last state: 'provisioning', timeout: 10m0s)
```
AFAICT, this was because the StateChangeConf func was returning `machineStateProvisioning` by default - not the actual state. Therefore, Terraform wasn't actually always able to tell if it had reached the desired state. By returning `inst.State` rather than assuming it was `provisioning`, I was able to get a more consistent test run.
```
HTTP_PROXY=http://127.0.0.1:8888 make testacc TEST=./triton …
```
=> resource/triton_machine: Fixing StateChangeConf issue with Creation

triton/data_source_image.go, triton/data_source_image_test.go, triton/image_sort.go, website/docs/d/triton_image.html.markdown
Fixes: #18
Will sort the images returned from the API and return the latest when
requested:
```
% make testacc TEST=./triton TESTARGS='-run=TestAccTritonImage_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./triton -v -run=TestAccTritonImage_ -timeout 120m
=== RUN   TestAccTritonImage_basic
--- PASS: TestAccTritonImage_basic (11.28s)
=== RUN   TestAccTritonImage_mostRecent
--- PASS: TestAccTritonImage_mostRecent (13.19s)
PASS
ok  	github.com/terraform-providers/terraform-provider-triton/triton	24.490s
```
=> data/image: Add support for `most_recent` to image data_source

triton/resource_machine.go, triton/resource_machine_test.go, website/docs/r/triton_machine.html.markdown
Ref: #19 
~*WIP*: This is a **work-in-progress PR** but I wanted to submit it in case anyone wanted to test. I cranked it out before the weekend and didn't do much testing/refactoring once I got the initial behavior in.~
This introduces the locality stanza. You'll only be able to use this on create as the data is never returned to Terraform after provisioning. However, so far, it's been working for me with the following configuration...
```hcl
provider "triton" {}
data "triton_image" "base" {
name    = "base-64"
os      = "smartos"
type    = "zone-dataset"
state   = "active"
version = "17.2.0"
}
data "triton_network" "public" {
name = "Joyent-SDC-Public"
}
resource "triton_machine" "base0" {
name = "bench-0"
package = "g4-highcpu-512M"
image = "${data.triton_image.base.id}"
nic {
network …
```
=> triton_machine: Introduce new Locality stanza

triton/resource_machine.go, triton/resource_machine_test.go, website/docs/r/triton_machine.html.markdown
Fixes: #30
There was an issue that when you specified a pool as a ni network id,
the provisioned network id would be different to that supplied to the
machine and thus create a perpetual diff
We decided that networks for the machine to be part of and nics attached
to the machine are different enough for them to be separate. Therefore,
we un-deprecated `networks` and we now pass a list of network ids for
the machine to be attached to
`nic` is now used as a computed parameter rather than an input. Meaning
we can do the following:
```
provider "triton" {}
data "triton_image" "image" {
name = "base-64-lts"
version = "16.4.1"
}
data "triton_network" "public" {
name = "Joyent-SDC-Public"
}
resource "triton_vlan" "test" {
vlan_id = 100
name = "test-vlan"
description = "test vlan"
}
resource …
```
=> resource/triton_machine: Fix issues with machine network diffs

triton/resource_fabric.go, triton/resource_machine.go, triton/tritonerr.go
My hope was to address some of the timing issues around deletions. The goal is to retry given a known error and continue to attempt provisioning until that error is gone. This has helped some of the known issues I've experienced in practice but has not fixed the issue under acceptance testing.
Sharing this for open feedback w/ @jen20 @stack72
=> Introduce retryOnError for retrying calls to Triton

vendor/github.com/joyent/triton-go/compute/instances.go, vendor/vendor.json
This includes the latest NPE patch within [joyent/triton-go](http://github.com/joyent/triton-go).
=> Bump triton-go to latest patch

README.md
Ref: #40 
User feedback demonstrated a glaring assumption that I had initially overlooked when documenting the provider, particularly in reference to `triton` CLI walk through not setting up `ssh-agent`. The following PR addresses not only all angles of configuring the provider but more links for documentation and usage.
/cc @neuroserve @misterbisson @heyawhite
=> docs: Clarify provider configuration and usage within README.md

triton/client.go, triton/provider.go, triton/resource_machine.go, triton/resource_machine_test.go, vendor/github.com/joyent/triton-go/compute/instances.go, vendor/vendor.json, website/docs/r/triton_machine.html.markdown
Ref: #32 ([comment](https://github.com/terraform-providers/terraform-provider-triton/issues/32#issuecomment-329029459)) as well as internal ticket PUBAPI-1428.
Triton team is deprecating `locality` in favor of the `affinity` rules feature ported from Docker API into CloudAPI's CreateMachine endpoint. This is still incoming but we're prepping for the release by integrating with the provider (coming to a CloudAPI near you).
We've introduced `affinity` argument to `triton_machine` like so...
```hcl
resource "triton_machine" "db" {
count = 2
name = "${format("db-%02d", count.index + 1)}"
package = "sample-128M"
image = "${data.triton_image.base.id}"
affinity = ["role!=database"]
tags {
role = "database"
}
}
```
The syntax used for rule definition are [publicly documented …
=> triton_machine: Introduce new affinity rules feature

triton/resource_firewall_rule_test.go, triton/resource_machine_test.go, triton/sweeper_test.go
Fixes: #46
This requires TRITON_ACCOUNT and TRITON_KEY_ID to be set. You must pass it a list of regions to run acess. It can take a comma separated list
Then it can be run as follows:
```
go test ./triton -v -sweep=us-sw-1,us-east-1
```
This gives us the output as follows:
```
2017/10/05 14:12:40 [DEBUG] Running Sweepers for region (us-sw-1):
2017/10/05 14:12:41 [DEBUG] Found 0 rules to sweep
2017/10/05 14:12:43 [DEBUG] Found 1 instances to sweep
2017/10/05 14:12:43 Destroying instance acctest-1533927144703045735
2017/10/05 14:12:44 Sweeper Tests ran:
- triton_firewall_rule
- triton_machine
ok      github.com/terraform-providers/terraform-provider-triton/triton    4.231s
```
=> Add sweepers for Triton Machines and Firewall Rules

website/docs/r/triton_machine.html.markdown
Fix the description of `id` attribute in triton_machine resource.
=> website: fix the description of id attribute of triton_machine

triton/data_source_account.go, triton/data_source_account_test.go, triton/provider.go, website/docs/d/triton_account.html.markdown, website/triton.erb
Fixes: #68
```
=== RUN   TestAccTritonAccount
--- PASS: TestAccTritonAccount (3.76s)
PASS
ok  	github.com/terraform-providers/terraform-provider-triton/triton	3.776s
```
=> datasource/triton_account: Adds a Triton Account DataSource

triton/data_source_datacenter.go, triton/data_source_datacenter_test.go, triton/provider.go, website/docs/d/triton_datacenter.html.markdown, website/triton.erb
Fixes: #69
```
terraform-provider-triton [triton-datacenter-datasource] % acctests triton TestAccTritonDataCenter
=== RUN   TestAccTritonDataCenter
--- PASS: TestAccTritonDataCenter (4.37s)
PASS
ok  	github.com/terraform-providers/terraform-provider-triton/triton	4.391s
```
=> datasource/datacenter: Adds a datasource for Triton datacenters

Gopkg.lock, Gopkg.toml, vendor/github.com/joyent/triton-go/CHANGELOG.md, vendor/github.com/joyent/triton-go/compute/instances.go, vendor/github.com/joyent/triton-go/storage/objects.go
Fixes: #64 
Changelog entry should read: 
```
resource/machine: Fixed a panic when network connection is dropped during a terraform refresh [#64]
```
=> dep/triton-go: Bump triton-go dependency to 0.4.2

triton/data_source_datacenter.go, triton/data_source_datacenter_test.go
```
terraform-provider-triton [master●] % acctests triton TestAccTritonDataCenter
=== RUN   TestAccTritonDataCenter
--- PASS: TestAccTritonDataCenter (4.68s)
=== RUN   TestAccTritonDataCenterOldUrl
--- PASS: TestAccTritonDataCenterOldUrl (4.66s)
PASS
ok  	github.com/terraform-providers/terraform-provider-triton/triton	9.362s
```
=> datasource/datacenter: Cater for old Joyent Cloud URLS in datasource

triton/sweeper_test.go
We hardcoded the url, we should use the env var. The value we pass to
the sweepers, just means that we can bypass the check to make sure a
region is present
The sweepers will now work in SPC :)
=> sweepers: Sweepers were tied to only work in the JPC

triton/resource_machine.go, triton/resource_machine_test.go, website/docs/r/triton_machine.html.markdown
Fixes: #87
```
terraform-provider-triton [master●] % acctests triton TestAccTritonMachine_basic
=== RUN   TestAccTritonMachine_basic
--- PASS: TestAccTritonMachine_basic (119.13s)
PASS
ok  	github.com/terraform-providers/terraform-provider-triton/triton	119.168s
```
=> resource/machine: Expose compute_node in machine resource

Gopkg.lock, Gopkg.toml, triton/data_source_package.go, triton/data_source_package_test.go, triton/provider.go, vendor/github.com/joyent/triton-go/CHANGELOG.md, vendor/github.com/joyent/triton-go/compute/packages.go, vendor/github.com/joyent/triton-go/compute/packages_test.go
This PR includes a new data source for pulling Package information out of Triton's CloudAPI. Looking for early feedback before I wrap up.
A Package in Triton specifies resources allocated to a machine instance. In order to run a compute instance a consumer must choose a package by various attributes like memory, disk, and swap size.
The HCL looks like this...
```hcl
provider "triton" {
insecure_skip_tls_verify = true
}
data "triton_package" "highcpu" {
filter {
name = "highcpu"
memory = 8192
}
}
data "triton_image" "image" {
name = "base-64-lts"
most_recent = true
}
resource "triton_machine" "test" {
name = "${format("test-%02d", count.index + 1)}"
package = "${data.triton_package.highcpu.name}"
image = "${data.triton_image.image.id}"
}
```
This currently evaluates to the following …
=> Introduce packages data source

triton/data_source_datacenter.go, triton/data_source_datacenter_test.go, website/docs/d/triton_datacenter.html.markdown
This commit updates the `triton_datacenter` data source with the following changes:
- Adds more logging at the debug level
- Adds more comments to the code
- Updates error messages
- Updates documentation
- Renames method and variable name as per the guideline at
https://github.com/golang/go/wiki/CodeReviewComments#initialisms
- Moves old Triton data centre URL to the right variable in the acceptance test
Signed-off-by: Krzysztof Wilczynski <kw@linux.com>
=> Update the triton_datacenter data source.

README.md
The triton provider needs go 1.9 to compile properly. 
When I tried to build v0.4.2 using Go 1.8.7 I got the following error:
```
+ make build
==> Checking that code complies with gofmt requirements...
go install
vendor/github.com/hashicorp/terraform/config/testing.go:9: t.Helper undefined (type *testing.T has no field or method Helper)
make: *** [GNUmakefile:7: build] Error 2
Traceback (most recent call last):
File "/opt/conda/bin/conda-build", line 6, in <module>
sys.exit(conda_build.cli.main_build.main())
File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 342, in main
execute(sys.argv[1:])
File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 333, in execute
noverify=args.no_verify)
File …
```
=> Update Go requirement to 1.9

triton/data_source_fabric_vlan.go, triton/data_source_fabric_vlan_test.go, triton/provider.go, triton/utils.go, triton/utils_test.go, triton/validators.go, triton/validators_test.go, website/docs/d/triton_fabric_vlan.html.markdown, website/triton.erb
This commit adds new data source called `triton_fabric_vlan`, which allows the
end-user to find details about a particular Fabric VLAN based on attributes such
as name, VLAN ID or description. Each of the attribute can be used as a filter
allowing to narrow down results more granularly (each filter creates an
implicit AND relationship with the other).
Additionally, this commit introduces a new `wildcardMatch` function that can be
used to perform simple pattern matches against a string value, and a function
`validateVLANIdentifier` that can be used in the schema where the `ValidateFunc`
is to be expected to verify whether the value for the Fabric VLAN ID is within
the correct range.
Signed-off-by: Krzysztof Wilczynski <kw@linux.com>
=> Add new `triton_fabric_vlan` data source.

triton/data_source_fabric_network.go, triton/data_source_fabric_network_test.go, triton/provider.go, website/docs/d/triton_fabric_network.html.markdown, website/triton.erb
This commit adds new data source called `triton_fabric_network`, which allows the
end-user to find details about a particular Fabric Network based on the unique name
of the network, which is used as a filter.
Signed-off-by: Krzysztof Wilczynski <kw@linux.com>
=> Add new `triton_fabric_network` data source.

website/docs/r/triton_machine.html.markdown
This commit adds more information about how to user the user data and user script
(clarifying the difference) and provides links to the relevant documentation which
provide more details about the metadata API, etc.
Signed-off-by: Krzysztof Wilczynski <kw@linux.com>
=> Add more details about how to use user data and user script.

triton/resource_fabric.go, triton/resource_fabric_migrate.go, triton/resource_fabric_migrate_test.go, website/docs/r/triton_fabric.html.markdown
Fixes: #100
As the underlying issue preventing this from working in CloudAPI has
been fixed, we are now defaulting to the same as CloudAPI
We have included a migration here to preserve backwards compatibility:
```
=== RUN   TestFabricMigrateState
2018/03/28 00:54:53 [INFO] Found Fabric State v0; migrating to v1
2018/03/28 00:54:53 [DEBUG] Attributes before Migration: map[string]string{"internet_nat":"true"}
2018/03/28 00:54:53 [DEBUG] Attributes after State Migration: map[string]string{"internet_nat":"true"}
2018/03/28 00:54:53 [INFO] Found Fabric State v0; migrating to v1
2018/03/28 00:54:53 [DEBUG] Attributes before Migration: map[string]string{}
2018/03/28 00:54:53 [DEBUG] Attributes after State Migration: map[string]string{"internet_nat":"false"}
--- PASS: TestFabricMigrateState …
```
=> resource/fabric: Default internet_nat to true

triton/resource_machine.go, website/docs/r/triton_machine.html.markdown
As per the change in CloudAPI, affinity is favoured over locality
Also, reordered the triton_machine schema to group similar together
=> resource/machine: Deprecate `locality` in favour of `affinity`

triton/resource_machine.go
Fix domain checks for SRV type CNS tags such as `servicefoo:1234`.
Introduce a split on `:` when comparing CNS tags against actual CNS DNS
short service names.
Without this fix the check never succeeds and results in terraform
timeouts.
Most of this is discussed here:
https://github.com/joyent/terraform-provider-triton/issues/108
=> Fix up SRV type CNS tag checks against domains

.golangci.yml, triton/client.go, triton/data_source_image.go, triton/data_source_image_test.go, triton/data_source_package.go, triton/data_source_volume.go, triton/data_source_volume_test.go, triton/provider.go, triton/resource_fabric.go, triton/resource_fabric_migrate.go, triton/resource_fabric_test.go, triton/resource_firewall_rule.go, triton/resource_key.go, triton/resource_key_test.go, triton/resource_machine.go, triton/resource_snapshot.go, triton/resource_volume.go, triton/tritonerr.go
Follow-up to: #145 with clean-up for various `make lint` checks.
Recommendation for reviewers: check commit by commit.
Note that a few `staticcheck` exclusions have been added, because these require a code refactor to use `context.Context`.
=> TRITON-2502: should pass all linter checks
